repositories:
- name: stable
  url: https://charts.helm.sh/stable/
- name: elastic
  url: https://helm.elastic.co
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: traefik
  url: https://helm.traefik.io/traefik
  
helmDefaults:
  tillerNamespace: helm
  tillerless: true

environments:
  default:
    values:
      - Namespace: "default"
