{{- if .Values.nodeport.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-example.fullname" . }}-nodeport
spec:
  type: NodePort
  selector:
    {{- include "my-example.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30031
{{- end }}